name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: |
          chmod +x ./gradlew
          ./gradlew build -x test --no-daemon
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag linhong4dockerhub/demo4dockerhub:$(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: linhong4dockerhub/demo4dockerhub
          tags: |
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
#          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}